// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class ChecklistItem
{
    public int ChItIdPk { get; set; }

    public int ChecklistFk { get; set; }

    public string Content { get; set; }

    public bool IsCompleted { get; set; }

    public int OrderIndex { get; set; }

    public virtual Checklist ChecklistFkNavigation { get; set; }
}