// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class Checklist
{
    public int ChIdPk { get; set; }

    public int? TripFk { get; set; }

    public int? TripDayFk { get; set; }

    public string Title { get; set; }

    public int OrderIndex { get; set; }

    public virtual ICollection<ChecklistItem> ChecklistItems { get; set; } = new List<ChecklistItem>();

    public virtual TripDay TripDayFkNavigation { get; set; }

    public virtual Trip TripFkNavigation { get; set; }
}