// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class ExpenseSplit
{
    public int ExSpIdPk { get; set; }

    public int ExpenseFk { get; set; }

    public int UserInfoFk { get; set; }

    public decimal Amount { get; set; }

    public virtual Expense ExpenseFkNavigation { get; set; }
}