// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class Expense
{
    public int ExIdPk { get; set; }

    public int TripFk { get; set; }

    public decimal Amount { get; set; }

    public DateTime? Date { get; set; }

    public int PaidByUserInfoFk { get; set; }

    public int? TripActivityFk { get; set; }

    public string Title { get; set; }

    public string Category { get; set; }

    public virtual ICollection<ExpenseSplit> ExpenseSplits { get; set; } = new List<ExpenseSplit>();

    public virtual UserInfo PaidByUserInfoFkNavigation { get; set; }

    public virtual TripActivity TripActivityFkNavigation { get; set; }

    public virtual Trip TripFkNavigation { get; set; }
}