// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Traces.Models;

public partial class Note
{
    public int NoIdPk { get; set; }

    public int? TripFk { get; set; }

    public string Content { get; set; }

    public int? OrderIndex { get; set; }

    public int? TripDayFk { get; set; }

    public virtual TripDay TripDayFkNavigation { get; set; }

    public virtual Trip TripFkNavigation { get; set; }
}