// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class Note
{
    public int NoIdPk { get; set; }

    public int? TripActivityFk { get; set; }

    public string Content { get; set; }

    public virtual TripActivity TripActivityFkNavigation { get; set; }
}