// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class PlaceDetail
{
    public int PlDetailPk { get; set; }

    public int? PlacesFk { get; set; }

    public string PhoneNumber { get; set; }

    public string Website { get; set; }

    public int? Rating { get; set; }

    public int? PriceLevel { get; set; }

    public string GoogleMapsUrl { get; set; }

    public int? UserRatingTotal { get; set; }

    public virtual Place PlacesFkNavigation { get; set; }
}