// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class PlacePhoto
{
    public int PlPhIdPk { get; set; }

    public int? PlacesFk { get; set; }

    public string GooglePhotoReference { get; set; }

    public string PhotoUrl { get; set; }

    public virtual Place PlacesFkNavigation { get; set; }
}