// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class PlaceCategory
{
    public int PlCaIdPk { get; set; }

    public string Name { get; set; }
}