// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class PlacePlaceCategory
{
    public int PlacesFk { get; set; }

    public int PlaceCategoriesFk { get; set; }

    public virtual PlaceCategory PlaceCategoriesFkNavigation { get; set; }

    public virtual Place PlacesFkNavigation { get; set; }
}