// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class PlaceHour
{
    public int PlHourIdPk { get; set; }

    public int? PlacesFk { get; set; }

    public int? DayOfWeek { get; set; }

    public int? OpenTime { get; set; }

    public int? CloseTime { get; set; }

    public virtual Place PlacesFkNavigation { get; set; }
}