// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class Place
{
    public int PlIdPk { get; set; }

    public string GooglePlaceId { get; set; }

    public string Name { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string PrimaryCategory { get; set; }

    public string FormattedAddress { get; set; }

    public string City { get; set; }

    public string CountryName { get; set; }

    public virtual ICollection<PlacePhoto> PlacePhotos { get; set; } = new List<PlacePhoto>();

    public virtual ICollection<TripActivity> TripActivities { get; set; } = new List<TripActivity>();
}