// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class RouteToNext
{
    public int RoNeIdPk { get; set; }

    public int FromActivityFk { get; set; }

    public int ToActivityFk { get; set; }

    public string TravelMode { get; set; }

    public int DistanceMeters { get; set; }

    public int DurationSeconds { get; set; }

    public string PolylineEncoded { get; set; }

    public virtual TripActivity FromActivityFkNavigation { get; set; }

    public virtual TripActivity ToActivityFkNavigation { get; set; }
}