// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Traces.Models;

public partial class TracesDbContext : DbContext
{
    public TracesDbContext()
    {
    }

    public TracesDbContext(DbContextOptions<TracesDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Checklist> Checklists { get; set; }

    public virtual DbSet<Note> Notes { get; set; }

    public virtual DbSet<Place> Places { get; set; }

    public virtual DbSet<PlaceCategory> PlaceCategories { get; set; }

    public virtual DbSet<PlaceDetail> PlaceDetails { get; set; }

    public virtual DbSet<PlaceHour> PlaceHours { get; set; }

    public virtual DbSet<PlacePhoto> PlacePhotos { get; set; }

    public virtual DbSet<PlacePlaceCategory> PlacePlaceCategories { get; set; }

    public virtual DbSet<RouteToNext> RouteToNexts { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

    public virtual DbSet<TripActivity> TripActivities { get; set; }

    public virtual DbSet<TripDay> TripDays { get; set; }

    public virtual DbSet<TripMember> TripMembers { get; set; }

    public virtual DbSet<UserInfo> UserInfos { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Checklist>(entity =>
        {
            entity.HasKey(e => e.ChIdPk).HasName("PK__Checklis__4E2CD300142B8236");

            entity.ToTable("Checklist");

            entity.Property(e => e.ChIdPk).ValueGeneratedNever();
            entity.Property(e => e.Content).HasMaxLength(100);
            entity.Property(e => e.TripActivityFk).HasColumnName("TripActivityFK");

            entity.HasOne(d => d.TripActivityFkNavigation).WithMany(p => p.Checklists)
                .HasForeignKey(d => d.TripActivityFk)
                .HasConstraintName("FK_Checklist_TripActivities");
        });

        modelBuilder.Entity<Note>(entity =>
        {
            entity.HasKey(e => e.NoIdPk).HasName("PK__Notes__14F9C02A6FC3F9F8");

            entity.Property(e => e.NoIdPk).ValueGeneratedNever();
            entity.Property(e => e.TripActivityFk).HasColumnName("TripActivityFK");

            entity.HasOne(d => d.TripActivityFkNavigation).WithMany(p => p.Notes)
                .HasForeignKey(d => d.TripActivityFk)
                .HasConstraintName("FK_Notes_TripActivities");
        });

        modelBuilder.Entity<Place>(entity =>
        {
            entity.HasKey(e => e.PlIdPk).HasName("PK__Places__C9D6A4C793E0371A");

            entity.HasIndex(e => e.GooglePlaceId, "UQ__Places__A19E0A9009A7C677").IsUnique();

            entity.Property(e => e.PlIdPk).ValueGeneratedNever();
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.CountryName).HasMaxLength(60);
            entity.Property(e => e.FormattedAddress).HasMaxLength(300);
            entity.Property(e => e.Latitude).HasColumnType("decimal(10, 8)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(11, 8)");
            entity.Property(e => e.Name).HasMaxLength(150);
            entity.Property(e => e.PrimaryCategory).HasMaxLength(20);
        });

        modelBuilder.Entity<PlaceCategory>(entity =>
        {
            entity.HasKey(e => e.PlCaIdPk).HasName("PK__PlaceCat__E0C65417E2FB4FC5");

            entity.Property(e => e.PlCaIdPk).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(30);
        });

        modelBuilder.Entity<PlaceDetail>(entity =>
        {
            entity.HasKey(e => e.PlDetailPk).HasName("PK__PlaceDet__80A720B4607A5B2D");

            entity.Property(e => e.PlDetailPk).ValueGeneratedNever();
            entity.Property(e => e.GoogleMapsUrl).HasMaxLength(400);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PlacesFk).HasColumnName("PlacesFK");
            entity.Property(e => e.Website).HasMaxLength(300);

            entity.HasOne(d => d.PlacesFkNavigation).WithMany(p => p.PlaceDetails)
                .HasForeignKey(d => d.PlacesFk)
                .HasConstraintName("FK_PlaceDetails_Places");
        });

        modelBuilder.Entity<PlaceHour>(entity =>
        {
            entity.HasKey(e => e.PlHourIdPk).HasName("PK__PlaceHou__A78D6AA3E4A8817D");

            entity.Property(e => e.PlHourIdPk).ValueGeneratedNever();
            entity.Property(e => e.PlacesFk).HasColumnName("PlacesFK");

            entity.HasOne(d => d.PlacesFkNavigation).WithMany(p => p.PlaceHours)
                .HasForeignKey(d => d.PlacesFk)
                .HasConstraintName("FK_PlaceHours_Places");
        });

        modelBuilder.Entity<PlacePhoto>(entity =>
        {
            entity.HasKey(e => e.PlPhIdPk).HasName("PK__PlacePho__B0E720042D9918D2");

            entity.Property(e => e.PlPhIdPk).ValueGeneratedNever();
            entity.Property(e => e.GooglePhotoReference).HasMaxLength(400);
            entity.Property(e => e.PlacesFk).HasColumnName("PlacesFK");

            entity.HasOne(d => d.PlacesFkNavigation).WithMany(p => p.PlacePhotos)
                .HasForeignKey(d => d.PlacesFk)
                .HasConstraintName("FK_PlacePhotos_Places");
        });

        modelBuilder.Entity<PlacePlaceCategory>(entity =>
        {
            entity.HasNoKey();

            entity.HasOne(d => d.PlaceCategoriesFkNavigation).WithMany()
                .HasForeignKey(d => d.PlaceCategoriesFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlacePlaceCategories_PlaceCategories");

            entity.HasOne(d => d.PlacesFkNavigation).WithMany()
                .HasForeignKey(d => d.PlacesFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlacePlaceCategories_Places");
        });

        modelBuilder.Entity<RouteToNext>(entity =>
        {
            entity.HasKey(e => e.RoNeIdPk);

            entity.ToTable("RouteToNext");

            entity.Property(e => e.PolylineEncoded).IsRequired();
            entity.Property(e => e.TravelMode)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.FromActivityFkNavigation).WithMany(p => p.RouteToNextFromActivityFkNavigations)
                .HasForeignKey(d => d.FromActivityFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FromActivity1");

            entity.HasOne(d => d.ToActivityFkNavigation).WithMany(p => p.RouteToNextToActivityFkNavigations)
                .HasForeignKey(d => d.ToActivityFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ToActivity2");
        });

        modelBuilder.Entity<Trip>(entity =>
        {
            entity.HasKey(e => e.TrIdPk);

            entity.ToTable("Trip");

            entity.Property(e => e.Description).HasMaxLength(150);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TripActivity>(entity =>
        {
            entity.HasKey(e => e.TrAcIdPk);

            entity.Property(e => e.EndTime).HasPrecision(0);
            entity.Property(e => e.StartTime).HasPrecision(0);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsFixedLength();

            entity.HasOne(d => d.PlaceFkNavigation).WithMany(p => p.TripActivities)
                .HasForeignKey(d => d.PlaceFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripActivities_Places");

            entity.HasOne(d => d.TripDayFkNavigation).WithMany(p => p.TripActivities)
                .HasForeignKey(d => d.TripDayFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripActivities_TripDay");
        });

        modelBuilder.Entity<TripDay>(entity =>
        {
            entity.HasKey(e => e.TrDaIdPk);

            entity.ToTable("TripDay");

            entity.HasOne(d => d.TripFkNavigation).WithMany(p => p.TripDays)
                .HasForeignKey(d => d.TripFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripDay_Trip");
        });

        modelBuilder.Entity<TripMember>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("TripMember");

            entity.HasOne(d => d.IdFkNavigation).WithMany()
                .HasForeignKey(d => d.IdFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripMember_UserInfo");

            entity.HasOne(d => d.TripFkNavigation).WithMany()
                .HasForeignKey(d => d.TripFk)
                .HasConstraintName("FK_TripMember_Trip");
        });

        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.HasKey(e => e.IdPk);

            entity.ToTable("UserInfo");

            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.UserFk)
                .IsRequired()
                .HasMaxLength(450);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}