// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Traces.Models;

public partial class TracesDbContext : DbContext
{
    public TracesDbContext(DbContextOptions<TracesDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Checklist> Checklists { get; set; }

    public virtual DbSet<ChecklistItem> ChecklistItems { get; set; }

    public virtual DbSet<Expense> Expenses { get; set; }

    public virtual DbSet<ExpenseSplit> ExpenseSplits { get; set; }

    public virtual DbSet<Note> Notes { get; set; }

    public virtual DbSet<Place> Places { get; set; }

    public virtual DbSet<PlacePhoto> PlacePhotos { get; set; }

    public virtual DbSet<RouteToNext> RouteToNexts { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

    public virtual DbSet<TripActivity> TripActivities { get; set; }

    public virtual DbSet<TripDay> TripDays { get; set; }

    public virtual DbSet<TripMember> TripMembers { get; set; }

    public virtual DbSet<UserInfo> UserInfos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Checklist>(entity =>
        {
            entity.HasKey(e => e.ChIdPk).HasName("PK__Checklis__4E2CD3008CDFBA7A");

            entity.ToTable("Checklist");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TripFk).HasColumnName("TripFK");

            entity.HasOne(d => d.TripDayFkNavigation).WithMany(p => p.Checklists)
                .HasForeignKey(d => d.TripDayFk)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Checklist_TripDay");

            entity.HasOne(d => d.TripFkNavigation).WithMany(p => p.Checklists)
                .HasForeignKey(d => d.TripFk)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Checklist_Trip");
        });

        modelBuilder.Entity<ChecklistItem>(entity =>
        {
            entity.HasKey(e => e.ChItIdPk).HasName("PK__Checklis__9637F8922B9DCA2E");

            entity.ToTable("ChecklistItem");

            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.ChecklistFkNavigation).WithMany(p => p.ChecklistItems)
                .HasForeignKey(d => d.ChecklistFk)
                .HasConstraintName("FK_ChecklistItem_Checklist");
        });

        modelBuilder.Entity<Expense>(entity =>
        {
            entity.HasKey(e => e.ExIdPk);

            entity.Property(e => e.ExIdPk).HasColumnName("ExIdPK");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Category).HasMaxLength(50);
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Title).HasMaxLength(100);

            entity.HasOne(d => d.PaidByUserInfoFkNavigation).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.PaidByUserInfoFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Expenses_UserInfo");

            entity.HasOne(d => d.TripActivityFkNavigation).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.TripActivityFk)
                .HasConstraintName("FK_Expenses_TripActivities");

            entity.HasOne(d => d.TripFkNavigation).WithMany(p => p.Expenses)
                .HasForeignKey(d => d.TripFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Expenses_Trip");
        });

        modelBuilder.Entity<ExpenseSplit>(entity =>
        {
            entity.HasKey(e => e.ExSpIdPk);

            entity.ToTable("ExpenseSplit");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.ExpenseFkNavigation).WithMany(p => p.ExpenseSplits)
                .HasForeignKey(d => d.ExpenseFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExpenseSplit_Expenses");
        });

        modelBuilder.Entity<Note>(entity =>
        {
            entity.HasKey(e => e.NoIdPk).HasName("PK__Notes__14F9C02A6FC3F9F8");

            entity.Property(e => e.Content).HasMaxLength(500);
            entity.Property(e => e.TripDayFk).HasColumnName("TripDayFK");
            entity.Property(e => e.TripFk).HasColumnName("TripFK");

            entity.HasOne(d => d.TripDayFkNavigation).WithMany(p => p.Notes)
                .HasForeignKey(d => d.TripDayFk)
                .HasConstraintName("FK_Notes_TripDay");

            entity.HasOne(d => d.TripFkNavigation).WithMany(p => p.Notes)
                .HasForeignKey(d => d.TripFk)
                .HasConstraintName("FK_Notes_TripActivities");
        });

        modelBuilder.Entity<Place>(entity =>
        {
            entity.HasKey(e => e.PlIdPk).HasName("PK__Places__C9D6A4C793E0371A");

            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.CountryName).HasMaxLength(60);
            entity.Property(e => e.FormattedAddress).HasMaxLength(300);
            entity.Property(e => e.Latitude).HasColumnType("decimal(10, 8)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(11, 8)");
            entity.Property(e => e.Name).HasMaxLength(150);
            entity.Property(e => e.PrimaryCategory).HasMaxLength(20);
        });

        modelBuilder.Entity<PlacePhoto>(entity =>
        {
            entity.HasKey(e => e.PlPhIdPk).HasName("PK__PlacePho__B0E720042D9918D2");

            entity.Property(e => e.PlacesFk).HasColumnName("PlacesFK");

            entity.HasOne(d => d.PlacesFkNavigation).WithMany(p => p.PlacePhotos)
                .HasForeignKey(d => d.PlacesFk)
                .HasConstraintName("FK_PlacePhotos_Places");
        });

        modelBuilder.Entity<RouteToNext>(entity =>
        {
            entity.HasKey(e => e.RoNeIdPk);

            entity.ToTable("RouteToNext");

            entity.Property(e => e.PolylineEncoded).IsRequired();
            entity.Property(e => e.TravelMode)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.FromActivityFkNavigation).WithMany(p => p.RouteToNextFromActivityFkNavigations)
                .HasForeignKey(d => d.FromActivityFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FromActivity1");

            entity.HasOne(d => d.ToActivityFkNavigation).WithMany(p => p.RouteToNextToActivityFkNavigations)
                .HasForeignKey(d => d.ToActivityFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ToActivity2");
        });

        modelBuilder.Entity<Trip>(entity =>
        {
            entity.HasKey(e => e.TrIdPk);

            entity.ToTable("Trip");

            entity.Property(e => e.Description).HasMaxLength(150);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TripActivity>(entity =>
        {
            entity.HasKey(e => e.TrAcIdPk);

            entity.Property(e => e.EndTime).HasPrecision(0);
            entity.Property(e => e.StartTime).HasPrecision(0);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsFixedLength();

            entity.HasOne(d => d.PlaceFkNavigation).WithMany(p => p.TripActivities)
                .HasForeignKey(d => d.PlaceFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripActivities_Places");

            entity.HasOne(d => d.TripDayFkNavigation).WithMany(p => p.TripActivities)
                .HasForeignKey(d => d.TripDayFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripActivities_TripDay");
        });

        modelBuilder.Entity<TripDay>(entity =>
        {
            entity.HasKey(e => e.TrDaIdPk);

            entity.ToTable("TripDay");

            entity.HasOne(d => d.TripFkNavigation).WithMany(p => p.TripDays)
                .HasForeignKey(d => d.TripFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripDay_Trip");
        });

        modelBuilder.Entity<TripMember>(entity =>
        {
            entity.HasKey(e => new { e.IdFk, e.TripFk });

            entity.ToTable("TripMember");

            entity.HasOne(d => d.IdFkNavigation).WithMany(p => p.TripMembers)
                .HasForeignKey(d => d.IdFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripMember_UserInfo");

            entity.HasOne(d => d.TripFkNavigation).WithMany(p => p.TripMembers)
                .HasForeignKey(d => d.TripFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripMember_Trip");
        });

        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.HasKey(e => e.IdPk);

            entity.ToTable("UserInfo");

            entity.Property(e => e.Email).HasMaxLength(200);
            entity.Property(e => e.UserFk)
                .IsRequired()
                .HasMaxLength(450);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}