// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class TripActivity
{
    public int TrAcIdPk { get; set; }

    public int TripDayFk { get; set; }

    public int PlaceFk { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public int OrderIndex { get; set; }

    public string Status { get; set; }

    public virtual Place PlaceFkNavigation { get; set; }

    public virtual ICollection<RouteToNext> RouteToNextFromActivityFkNavigations { get; set; } = new List<RouteToNext>();

    public virtual ICollection<RouteToNext> RouteToNextToActivityFkNavigations { get; set; } = new List<RouteToNext>();

    public virtual TripDay TripDayFkNavigation { get; set; }
}