// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class TripDay
{
    public int TrDaIdPk { get; set; }

    public int TripFk { get; set; }

    public int? DayNumber { get; set; }

    public DateOnly Date { get; set; }

    public virtual ICollection<TripActivity> TripActivities { get; set; } = new List<TripActivity>();

    public virtual Trip TripFkNavigation { get; set; }
}