// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class TripMember
{
    public int IdFk { get; set; }

    public int TripFk { get; set; }

    public virtual UserInfo IdFkNavigation { get; set; }

    public virtual Trip TripFkNavigation { get; set; }
}