// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class Trip
{
    public int TrIdPk { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public double? Budget { get; set; }

    public virtual ICollection<Checklist> Checklists { get; set; } = new List<Checklist>();

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<Note> Notes { get; set; } = new List<Note>();

    public virtual ICollection<TripDay> TripDays { get; set; } = new List<TripDay>();

    public virtual ICollection<TripMember> TripMembers { get; set; } = new List<TripMember>();
}