// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class UserInfo
{
    public int IdPk { get; set; }

    public string UserFk { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
}