// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Traces.Models;

public partial class UserInfo
{
    public int IdPk { get; set; }

    public string UserFk { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<TripMember> TripMembers { get; set; } = new List<TripMember>();
}